export const businessProfile = Object.freeze({
  publicName: 'Trockenbau PrimaVista Schweiz',
  legalName: 'Prima Vista B&G GmbH',
  serviceLine: 'Trockenbau • Innenausbau • Renovationen',
  slogan: 'Präzision. Qualität. Zeitloses Design.',
  email: 'info@trockenbau-primavista.ch',
  phone: '+41 78 265 93 32',
  phoneHref: 'tel:+41782659332',
  whatsapp: 'https://wa.me/491793596697',
  instagram: 'https://www.instagram.com/trockenbau_primavista.ch/',
  website: 'https://trockenbau-primavista.ch/',
  contactHours: 'Mo–Fr 08:00–17:00 · Sa nach Vereinbarung · So geschlossen',
  appointmentNote: 'Persönliche Beratungen und Termine erfolgen nach Vereinbarung.',
  address: Object.freeze({
    streetAddress: 'Spinnereistrasse 5',
    postalCode: '6020',
    addressLocality: 'Emmenbrücke',
    addressCountry: 'CH',
  }),
  serviceAreas: Object.freeze([
    'Luzern',
    'Kriens',
    'Horw',
    'Emmen',
    'Emmenbrücke',
    'Ebikon',
    'Rothenburg',
    'Buchrain',
    'Root',
    'Adligenswil',
    'Meggen',
    'Sursee',
    'Sempach',
    'Zug',
    'Baar',
    'Cham',
    'Rotkreuz',
    'Küssnacht am Rigi',
    'Stans',
    'Stansstad',
    'Altdorf',
    'Zürich und Umgebung',
  ]),
});

export const localBusinessSchema = Object.freeze({
  '@context': 'https://schema.org',
  '@type': 'HomeAndConstructionBusiness',
  '@id': `${businessProfile.website}#business`,
  name: businessProfile.publicName,
  legalName: businessProfile.legalName,
  slogan: businessProfile.slogan,
  description:
    'Trockenbau, Innenausbau und Renovationen für Luzern, die Zentralschweiz '
    + 'sowie Zürich und Umgebung.',
  url: businessProfile.website,
  logo: `${businessProfile.website}pwa-512x512.png`,
  email: businessProfile.email,
  telephone: businessProfile.phone,
  sameAs: [businessProfile.instagram],
  address: {
    '@type': 'PostalAddress',
    ...businessProfile.address,
  },
  areaServed: businessProfile.serviceAreas,
  hasOfferCatalog: {
    '@type': 'OfferCatalog',
    name: 'Trockenbau-, Innenausbau- und Renovationsleistungen',
    itemListElement: [
      'Decken abhängen',
      'Wände und Vorsatzwände stellen',
      'Trockenestrich und Bodenaufbau',
      'Dachschrägen ausbauen',
      'Dämmung und Brandschutz',
      'Innenausbau und Renovationen',
    ].map((name) => ({
      '@type': 'Offer',
      itemOffered: {
        '@type': 'Service',
        name,
      },
    })),
  },
});
